# Generated by Django 3.2.7 on 2022-09-28 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_highlights'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highlights',
            new_name='Highlight',
        ),
    ]
