# Generated by Django 3.2.7 on 2022-09-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_highlights_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='upcoming/')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='upcoming/')),
            ],
        ),
    ]
